SELECT 
:P_NUNOTA AS NUNOTA,
AMP.CODPRODMP,
AMP.CONTROLEMP,
CASE
    WHEN AMP.QTD = 0 THEN AMP.AD_QTDAPONTADAORIG
    ELSE AMP.QTD
END AS QTD,
NVL((SELECT MAX(VLRUNIT) FROM TGFITE WHERE NUNOTA = :P_NUNOTA AND CODPROD = AMP.CODPRODMP),0) AS VLRUNIT,
NVL(CASE
    WHEN AMP.QTD = 0 THEN AMP.AD_QTDAPONTADAORIG
    ELSE AMP.QTD
END * (SELECT MAX(VLRUNIT) FROM TGFITE WHERE NUNOTA = :P_NUNOTA AND CODPROD = AMP.CODPRODMP),0) AS VLRTOT,
AMP.CODLOCALBAIXA,
AMP.CODVOL
FROM TPRAMP AMP 
WHERE AMP.NUAPO = :P_NUAPO
AND CASE
    WHEN AMP.QTD = 0 THEN AMP.AD_QTDAPONTADAORIG
    ELSE AMP.QTD
END  > 0

UNION ALL

SELECT DISTINCT
:P_NUNOTA AS NUNOTA,
AMP.CODPRODMP,
' ' AS CONTROLE,
AMP.AD_QTDAPONTADAORIG - (SELECT SUM(A.QTD) FROM TPRAMP A WHERE A.NUAPO = :P_NUAPO AND A.CODPRODMP = AMP.CODPRODMP) AS QTD,
NVL((SELECT MAX(VLRUNIT) FROM TGFITE WHERE NUNOTA = :P_NUNOTA AND CODPROD = AMP.CODPRODMP),0) AS VLRUNIT,
NVL((AMP.AD_QTDAPONTADAORIG - (SELECT SUM(A.QTD) FROM TPRAMP A WHERE A.NUAPO = :P_NUAPO AND A.CODPRODMP = AMP.CODPRODMP)) * (SELECT MAX(VLRUNIT) FROM TGFITE WHERE NUNOTA = :P_NUNOTA AND CODPROD = AMP.CODPRODMP),0) AS VLRTOT,
AMP.CODLOCALBAIXA,
AMP.CODVOL
FROM TPRAMP AMP 


WHERE AMP.NUAPO = :P_NUAPO
AND AMP.QTD > 0


HAVING (SELECT MIN(A.AD_QTDAPONTADAORIG) FROM TPRAMP A WHERE NUAPO = :P_NUAPO AND CODPRODMP = AMP.CODPRODMP) > SUM(AMP.QTD)
AND AMP.AD_QTDAPONTADAORIG - (SELECT SUM(A.QTD) FROM TPRAMP A WHERE A.NUAPO = :P_NUAPO AND A.CODPRODMP = AMP.CODPRODMP) > 0
GROUP BY 
AMP.CODPRODMP,
AMP.CODLOCALBAIXA,
AMP.CODVOL,
AMP.AD_QTDAPONTADAORIG

