SELECT
  T.CODPROD,
/*WHERECONTROLE   T.CONTROLE, WHERECONTROLE*/
  SUM(T.QTDPEDIDO) AS QTDPEDIDO,
  SUM(T.QTDCONF) AS QTDCONFERIDA
  FROM (
	SELECT
		ITE.CODPROD,
		ITE.CONTROLE AS CONTROLE,
		SUM(ITE.QTDNEG) AS QTDPEDIDO,
		0 AS QTDCONF
	FROM TGFITE ITE
      INNER JOIN TGFPRO PRO ON(PRO.CODPROD = ITE.CODPROD)
	WHERE ITE.NUNOTA = :NUNOTA
	  AND ITE.SEQUENCIA > 0
      AND NVL(PRO.AD_SEPARAPROD, 'N') = 'N'
	GROUP BY ITE.CODPROD, ITE.CONTROLE
	
	UNION
	
	SELECT 
		COI2.CODPROD,
		COI2.CONTROLE AS CONTROLE,
		0 AS QTDPEDIDO,
		SUM(COI2.QTDUNITPADRAO) AS QTDCONF
	FROM  AD_TRASITEMCONF COI2 
	WHERE NUCONF = :NUCONF
	GROUP BY COI2.CODPROD, COI2.CONTROLE
)T
/*WHEREPRODUTO WHERE T.CODPROD = :CODPROD WHEREPRODUTO*/
GROUP BY T.CODPROD
/*WHERECONTROLE , T.CONTROLE WHERECONTROLE*/

